#!/usr/bin/env sh

alias pacaur='pacaur --color=auto --noedit'

alias aur=pacaur

# search packages
alias aurs='pacaur -s'

# install packages
alias auri='pacaur -y'

# show package information
alias aursh='pacaur -i'

# upgrade installed packages
alias aurup='pacaur -yu'
