#!/usr/bin/env bash

set -eu

# Add file system modifications.
sudo rsync -v --archive --no-owner --no-group ./files/root/ /

# Enable old kernel module cleanup.
sudo systemctl enable --now linux-modules-cleanup.service

# Enable ad-hoc job scheduling.
sudo systemctl enable --now atd.service

# Enable package file indexing.
sudo systemctl enable --now pkgfile-update.timer
sudo pkgfile --update

# Enable file system indexing.
sudo systemctl enable --now plocate-updatedb.timer

# Allow users in locate group to update locate database.
sudo chgrp -R locate /var/lib/plocate
sudo chmod -R g+w /var/lib/plocate

# Only enable power saving if a battery exists.
if [[ -e /sys/class/power_supply/BAT0 ]]; then
    sudo pacman --sync --noconfirm --needed tlp
    sudo systemctl enable tlp.service
fi

# Enable ssh-agent for this user at login.
systemctl --user enable --now ssh-agent.service
