#!/usr/bin/env bash

set -eu

sudo rsync -v --archive --no-owner --no-group ./rootfs/ /

sudo systemctl enable --now atd.service

sudo systemctl enable --now pkgfile-update.timer
sudo pkgfile --update

sudo systemctl enable --now plocate-updatedb.timer
sudo gpasswd --add "$USER" locate

# Allow users in locate group to run updatedb.
sudo chgrp -R locate /var/lib/plocate
sudo chmod -R g+w /var/lib/plocate

systemctl --user enable --now ssh-agent.service
