#!/usr/bin/env bash

set -euo pipefail

# Ensure that certain /etc/skel files don't interfere with stow's symlinks.
rm -f ~/.bashrc ~/.bash_profile ~/.bash_logout

stow --no-folding --dir ./files --target ~ --restow home
