#!/usr/bin/env bash

set -eu

# Ensure that the /etc/skel files don't interfere with stow's symlinks.
rm -f ~/.bashrc ~/.bash_profile ~/.bash_logout

stow --no-folding --dir ./files --target ~ --restow home
