#!/usr/bin/env bash

set -eu

export PATH=$PWD/stow/.local/bin:$PATH

sudo pacman --sync --noconfirm --needed - <./packages/pacman

if ! which pikaur >/dev/null; then
    aur-install pikaur
fi

pikaur --sync --noconfirm --needed - <./packages/aur
