#!/usr/bin/env bash

set -eu

name=${1:-}

pacman_list=$PWD/packages/pacman${name:+-$name}
aur_list=$PWD/packages/aur${name:+-$name}

if [[ -f $pacman_list ]]; then
    sudo cat "$pacman_list" | sudo pacman -S --noconfirm --needed -
fi

export PATH=$PWD/stow/.local/bin:$PATH

if [[ -f $aur_list ]]; then
    if [[ ! -x /usr/bin/pikaur ]]; then
        enable-pikaur
    fi
    pikaur -S --noconfirm --needed - <"$aur_list"
fi
