#!/usr/bin/env bash

# Selects a random Mullvad relay based on optional location criteria.

set -euo pipefail

die() {
    printf "%s: line %s: %s\n" "$0" "${BASH_LINENO[0]}" "$1" >&2
    exit "${2:-1}"
}

config_file=/usr/local/etc/mullvad/location.conf

if [[ -f $config_file ]]; then
    . "$config_file" || die "unable to source file: $config_file"
fi

declare -a jq_options=()

if [[ -v COUNTRY && -v CITY ]]; then
    jq_options=(--arg country "$COUNTRY" --arg city "$CITY")
    jq_filter='.countries | map(select(.code == $country)) | first | .cities | map(select(.code == $city)) | first | .relays | map(.hostname) | .[]'
elif [[ -v COUNTRY ]]; then
    jq_options=(--arg country "$COUNTRY")
    jq_filter='.countries | map(select(.code == $country)) | map(.cities) | .[] | map(.relays) | flatten | map(.hostname) | .[]'
else
    jq_filter='.countries | map(.cities) | .[] | map(.relays) | flatten | map(.hostname) | .[]'
fi

interface=wg-mullvad
config_dir=/etc/wireguard
config_file=$config_dir/$interface.conf

relay_hostname=$(jq -r "${jq_options[@]}" "$jq_filter" /usr/local/share/mullvad/relays.json | shuf -n1)

[[ -n $relay_hostname ]] || die "no relays found"

relay_config_file=$config_dir/mullvad-${relay_hostname%-wireguard}.conf

[[ -f $relay_config_file ]] || die "configuration file does not exist: $relay_config_file"

ln -svfn "$relay_config_file" "$config_file"
