#!/usr/bin/env bash

set -euo pipefail

error() {
    local format=$1
    shift
    printf "%s: line %d: $format\n" "$0" "${BASH_LINENO[0]}" "$@" >&2
}

die() {
    error "$@"
    exit 1
}

account=$1

private_key=$(wg genkey)
public_key=$(wg pubkey <<<"$private_key")

response=$(curl -sSL -d account="$account" --data-urlencode pubkey="$public_key" https://api.mullvad.net/wg/) || die "Unable to connect to Mullvad API"
[[ $response =~ ^[0-9a-f:/.,]+$ ]] || die "$response"
address=$response

config_file=/usr/local/etc/mullvad/client.conf

mkdir -p "$(dirname "$config_file")"

umask 077

cat >"$config_file" <<EOF
PRIVATE_KEY=$private_key
ADDRESS=$address
EOF
